FORMAT: 1A
HOST: https://candidates-information.herokuapp.com/

# Candidates Info.
It's a simple API allowing consumers to view information of candidates.

##Candidates Information [/ppets]

### List All Candidates[GET]

+ response 200 (application/json)

           ("message":"Hello Apiary World!")


### Add a new Candidates Information [POST]

Thanks for using our app.

+ response 200 (application/json)

        {
            "": "Candidates:",
        [
        {
            "_id": "5cbd8ab3e4041310c8861577",
            "name": "Liam",
            "regestration": "171115865",
            "college": "siamese",
            "session": "2016-17"
        },
        {
            "_id": "5cbd8bade4041333e8dc5cca",
            "name": "Liami",
            "regestration": "1711195865",
            "college": "siamiese",
            "session": "2016-917"
        },
        {
            "_id": "5cbd8c81e4041330e8898c25",
            "name": "nahid",
            "regestration": "1711076136",
            "college": "midc",
            "session": "2016-17"
        },
        {
            "_id": "5cbd8c9ae4041330e8898c26",
            "name": "nadim",
            "regestration": "1711076111",
            "college": "rajshahi college",
            "session": "2016-17"
        },
        {
            "_id": "5cbd8cb1e4041330e8898c27",
            "name": "shuvo",
            "regestration": "1710776125",
            "college": "Purbadala college",
            "session": "2016-17"
        }
        ]
        }